name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create files
      run: mkdir tools | mkdir php-cs-fixer
      
    - name: Install dependencies
      run: composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer
      
    - name: Run Linter
      run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix . --dry-run

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
